<?php

namespace Tests;

use App\Models\User;
use Illuminate\Foundation\Testing\TestCase as BaseTestCase;
use Illuminate\Testing\TestResponse;

abstract class TestCase extends BaseTestCase
{
    use CreatesApplication;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->withoutExceptionHandling();

        TestResponse::macro('data', function ($key) {
            // 通过 $this->original->getData() 可以获取到绑定给视图的原始数据

            return $this->original->getData()[$key];
        });
    }

    protected function signIn($user = null): TestCase
    {
        $user = $user ?: create(User::class);
        $this->actingAs($user);
        return $this;
    }
}
